### ISSUE TITLE
Contract edges by dragging one point on the other [FEATUREREQ]

### ISSUE THREAD

**Issue by elsamuray7** [elsamuray7/Minorfinder#18]
**Is your feature request related to a problem? Please describe.**
Simon Tatham mentioned that it annoys him that the _dominant_ point in a contraction changes its position (it will move half way along the edge).
Furthermore he stated that the heuristic doesn't work perfect (thats especially annoying for edge contractions because thats the most common move rather than edge deletions ). I must say that I didn't experience any problems with the UI choosing wrong edges so I am not sure whether its really the fault of the heuristic.

**Describe the behaviour you'd like**
To be able to decide where the new point should lie when an edge is contracted, one should be able to drag one point on the other to specifiy the position of the new point, i.e. the dragged point will move into the other one.

**Suggestions**
- The most suitable solution would be to convert a `MOVE_DRAGPOINT` in `interpret_move()` into a `MOVE_CONTREDGE` if the dragged point overlays any other point (and convert it back if the dragged point doesn't overlay anymore)
- We must be careful because the _dominant_ point can have a higher index than the _recessive_ one now. I don't remember whether the implementation ever relies on the fact that we've always merged into the vertex with the smaller index so far.
- For the edge deletion and the problem with the UI making the wrong choice we maybe need to play with the `EDGE_TRESHOLD` parameter

**Additional context**
Moreover it would be cool that either in general when one hovers over a point or only when one point is dragged on the other, the point changes its radius to indicate that the player is able to make a move now (or that it detects a possible move that would be done if the player releases their mouse click).
Last but not least a little thing: The drag point hides behind points with bigger index because they are drawn later. We should take untangle as role model where the drag point never hides behind any point.

**Comment by N-Harsha** [comment]
i am a newbie and want work on this issue so please could you point me in the right direction
