### ISSUE TITLE
Delete vertices of any degree [FEATUREREQ]

### ISSUE THREAD

**Issue by elsamuray7** [elsamuray7/Minorfinder#20]
**Is your feature request related to a problem? Please describe.**
Simon Tatham stated that its annoying that the player has to remove all edges of a vertex to delete them. To be honest I've already played with the idea to change that but yet I wasn't sure. Someone else mentioning this problem was the confirmation I needed.

**Describe the behaviour you'd like**
The player can remove vertices together with all their incident edges in one move.

**Suggestions**
A method very much like `delete_edge()` where the vertex is removed from the 234-tree of visible vertices and all edges that are incident to it are removed from the 234-tree of edges. Though we must not forget to decrease the opposite vertices degrees or otherwise we can't correctly determine whether a game has been solved or not anymore.

**Additional context**
We should definitely think about removing vertices with no incident edges automatically since they are definitely not part of any valid solution.

**Comment by ravindrabhargava** [comment]
Hi Please assign me this
